### ISSUE TITLE
 Says File google-services.json is missing. The Google Services Plugin cannot function without it. 

### ISSUE THREAD

**Issue by engineeringstudent0012** [shockbytes/Corey#25]
![Screenshot (106)](https://user-images.githubusercontent.com/52909024/97801432-d1607900-1c64-11eb-8bfb-eeb21dcb1a2f.png)

**Comment by engineeringstudent0012** [comment]
Just Needed To Add google-services.json

**Comment by shockbytes** [comment]
Hey @engineeringstudent0012!

The repository is more or less for my personal usage, meaning all data stored in Firebase only belong to me and the setup does not even allow 2 separate accounts to function properly. 

If you want to run Corey, you're free fork it, create an own Firebase project and link it with your own `google-services.json`. In this case, you will host your own data in your own Firebase instance.
